import type { MatchableProfile } from "./types";

/* ═══════════════════════════════════════════════════════════
   Demo Matchable Profiles
   ─────────────────────────────────────────────────────────
   Used during development before real database integration.
   ═══════════════════════════════════════════════════════════ */

export const DEMO_USER: MatchableProfile = {
  id: "user-self",
  displayName: "You",
  username: "you",
  avatarUrl: null,
  campus: "IIT Delhi",
  stream: "Computer Science",
  year: "3rd Year",
  bio: "Full-stack dev learning ML",
  skillsToTeach: ["React", "TypeScript", "Next.js", "Node.js", "System Design"],
  skillsToLearn: ["Machine Learning", "Python", "Docker", "Rust"],
  goals: ["Master a new skill", "Help others learn", "Build projects together"],
  learningStyle: "Hands-on",
  availability: ["Evening", "Night"],
  preferredLanguage: "English",
  dnaTraits: [
    { trait: "Clarity of explanation", score: 0.92, category: "teaching" },
    { trait: "Patience", score: 0.88, category: "teaching" },
    { trait: "Problem solving", score: 0.78, category: "learning" },
    { trait: "Collaboration", score: 0.90, category: "social" },
  ],
  knowledgeCredits: 1420,
  trustScore: 4.8,
  totalSessions: 65,
  avgRating: 4.8,
  streak: 12,
  energyMode: "social",
  isOnline: true,
  lastActiveAt: new Date().toISOString(),
};

export const DEMO_CANDIDATES: MatchableProfile[] = [
  {
    id: "user-1",
    displayName: "Ananya Sharma",
    username: "ananya_s",
    avatarUrl: null,
    campus: "IIT Delhi",
    stream: "Computer Science",
    year: "3rd Year",
    bio: "ML researcher & Python enthusiast. Love teaching math concepts.",
    skillsToTeach: ["Python", "Machine Learning", "Linear Algebra", "TensorFlow"],
    skillsToLearn: ["React", "TypeScript", "System Design"],
    goals: ["Master a new skill", "Help others learn", "Prepare for placements"],
    learningStyle: "Visual",
    availability: ["Evening", "Night", "Late Night"],
    preferredLanguage: "English",
    dnaTraits: [
      { trait: "Clarity of explanation", score: 0.95, category: "teaching" },
      { trait: "Patience", score: 0.91, category: "teaching" },
      { trait: "Problem solving", score: 0.88, category: "learning" },
      { trait: "Active listening", score: 0.85, category: "social" },
    ],
    knowledgeCredits: 2150,
    trustScore: 4.9,
    totalSessions: 89,
    avgRating: 4.9,
    streak: 21,
    energyMode: "teaching",
    isOnline: true,
    lastActiveAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: "user-2",
    displayName: "Rahul Verma",
    username: "rahul_v",
    avatarUrl: null,
    campus: "IIT Delhi",
    stream: "AI / Machine Learning",
    year: "2nd Year",
    bio: "Deep learning nerd. Building side projects 24/7.",
    skillsToTeach: ["Python", "Deep Learning", "Docker", "AWS"],
    skillsToLearn: ["React", "Next.js", "TypeScript", "System Design"],
    goals: ["Build projects together", "Win hackathons", "Master a new skill"],
    learningStyle: "Hands-on",
    availability: ["Night", "Late Night", "Weekends"],
    preferredLanguage: "English",
    dnaTraits: [
      { trait: "Problem solving", score: 0.92, category: "learning" },
      { trait: "Adaptability", score: 0.85, category: "social" },
      { trait: "Consistency", score: 0.80, category: "learning" },
    ],
    knowledgeCredits: 890,
    trustScore: 4.5,
    totalSessions: 34,
    avgRating: 4.6,
    streak: 7,
    energyMode: "learning",
    isOnline: true,
    lastActiveAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: "user-3",
    displayName: "Priya Nair",
    username: "priya_n",
    avatarUrl: null,
    campus: "NIT Trichy",
    stream: "Computer Science",
    year: "4th Year",
    bio: "Full-stack dev. Placement-prepping. Love DSA.",
    skillsToTeach: ["JavaScript", "Node.js", "MongoDB", "DSA"],
    skillsToLearn: ["System Design", "React", "TypeScript"],
    goals: ["Prepare for placements", "Help others learn", "Stay consistent with studies"],
    learningStyle: "Reading/Writing",
    availability: ["Morning", "Afternoon", "Evening"],
    preferredLanguage: "English",
    dnaTraits: [
      { trait: "Beginner-friendliness", score: 0.90, category: "teaching" },
      { trait: "Consistency", score: 0.88, category: "learning" },
      { trait: "Collaboration", score: 0.82, category: "social" },
    ],
    knowledgeCredits: 1680,
    trustScore: 4.7,
    totalSessions: 72,
    avgRating: 4.7,
    streak: 15,
    energyMode: "focused",
    isOnline: false,
    lastActiveAt: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: "user-4",
    displayName: "Arjun Mehta",
    username: "arjun_m",
    avatarUrl: null,
    campus: "IIT Delhi",
    stream: "Computer Science",
    year: "3rd Year",
    bio: "Competitive programmer. Rust enthusiast.",
    skillsToTeach: ["C++", "Algorithms", "Competitive Programming", "Rust"],
    skillsToLearn: ["Machine Learning", "System Design", "Docker"],
    goals: ["Win hackathons", "Master a new skill", "Build projects together"],
    learningStyle: "Hands-on",
    availability: ["Evening", "Night"],
    preferredLanguage: "English",
    dnaTraits: [
      { trait: "Problem solving", score: 0.96, category: "learning" },
      { trait: "Accuracy", score: 0.93, category: "teaching" },
      { trait: "Active listening", score: 0.72, category: "social" },
    ],
    knowledgeCredits: 1120,
    trustScore: 4.6,
    totalSessions: 45,
    avgRating: 4.5,
    streak: 9,
    energyMode: "focused",
    isOnline: true,
    lastActiveAt: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: "user-5",
    displayName: "Sneha Patel",
    username: "sneha_p",
    avatarUrl: null,
    campus: "VIT Vellore",
    stream: "Data Science",
    year: "2nd Year",
    bio: "Data science student. Love visualizations.",
    skillsToTeach: ["Python", "Statistics", "Data Visualization", "Pandas"],
    skillsToLearn: ["React", "JavaScript", "SQL"],
    goals: ["Master a new skill", "Help others learn", "Grow my network"],
    learningStyle: "Visual",
    availability: ["Afternoon", "Evening"],
    preferredLanguage: "Hindi",
    dnaTraits: [
      { trait: "Patience", score: 0.94, category: "teaching" },
      { trait: "Clarity of explanation", score: 0.86, category: "teaching" },
      { trait: "Collaboration", score: 0.88, category: "social" },
    ],
    knowledgeCredits: 560,
    trustScore: 4.3,
    totalSessions: 22,
    avgRating: 4.4,
    streak: 5,
    energyMode: "social",
    isOnline: true,
    lastActiveAt: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: "user-6",
    displayName: "Vikram Singh",
    username: "vikram_s",
    avatarUrl: null,
    campus: "IIT Delhi",
    stream: "Electrical Engineering",
    year: "4th Year",
    bio: "Embedded systems + web dev crossover. Mentor at coding club.",
    skillsToTeach: ["C", "Embedded Systems", "Python", "Git"],
    skillsToLearn: ["React", "Next.js", "Cloud Architecture"],
    goals: ["Help others learn", "Prepare for placements", "Grow my network"],
    learningStyle: "Auditory",
    availability: ["Morning", "Evening", "Weekends"],
    preferredLanguage: "English",
    dnaTraits: [
      { trait: "Beginner-friendliness", score: 0.95, category: "teaching" },
      { trait: "Patience", score: 0.92, category: "teaching" },
      { trait: "Active listening", score: 0.90, category: "social" },
      { trait: "Adaptability", score: 0.88, category: "social" },
    ],
    knowledgeCredits: 2340,
    trustScore: 4.9,
    totalSessions: 105,
    avgRating: 4.9,
    streak: 28,
    energyMode: "teaching",
    isOnline: false,
    lastActiveAt: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
];
